[package]
name = "core-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
opencv = { version = "0.94.2", features = ["clang-runtime"] }

[dependencies.async-std]
version = "1.7.0"
features = ["attributes"]